authors:
  Emir C.:
    name: Emir C.
    description : Conseiller en médiation technologique
    avatar : e
  Indiana D. :
    name: Indiana Delsart
    description : Bibliothécaire
    avatar : e
  Jérémy P. : 
    name : Jérémy Prime 
    description : Technicien en documentation
    avatar : e